### ISSUE TITLE
How do i fix this error

### ISSUE THREAD

**Issue by RootWeewx** [0xB9/MyBBscan#1]
Traceback (most recent call last):
  File "scan.py", line 165, in <module>
    scan(site, upload)
  File "scan.py", line 51, in scan
    status = connection_status(site, "/inc/plugins/"+upload)
  File "scan.py", line 46, in connection_status
    connection.request("HEAD", plugin_file)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

**Comment by 0xB9** [comment]
Sorry for the late reply... but it looks like you added the `https://` when entering the URL which isn't needed. Just enter the domain & nothing else like shown in the example. 
![bbscan-ex](https://user-images.githubusercontent.com/33612375/48973385-34265000-f00c-11e8-8e9d-af4d38a2ca1a.png)


That should fix your issue so I'm going to close this for now, feel free to reopen if you continue to see the error.

**Comment by 0xB9** [comment]
Fixed in https://github.com/0xB9/MyBBscan/commit/255698b5a2564688dfb78232a3b7a9f9621f191b
