### ISSUE TITLE
Scanner doesn't work with ip adresses

### ISSUE THREAD

**Issue by jun3d4y** [0xB9/MyBBscan#2]
Hello, great work !
Unfortunatly I can't use it with backend ip adresses.

`Traceback (most recent call last):
  File ".\scan.py", line 223, in <module>
    scan(site, upload)
  File ".\scan.py", line 59, in scan
    status = connection_status(site, "/inc/plugins/"+upload)
  File ".\scan.py", line 54, in connection_status
    connection.request("HEAD", plugin_file)
  File "C:\Users\champip0p\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\champip0p\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\champip0p\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\champip0p\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1006, in _send_output
    self.send(msg)
  File "C:\Users\champip0p\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 946, in send
    self.connect()
  File "C:\Users\champip0p\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1402, in connect
    super().connect()
  File "C:\Users\champip0p\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 917, in connect
    self.sock = self._create_connection(
  File "C:\Users\champip0p\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\champip0p\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)`

**Comment by 0xB9** [comment]
Hi, thanks for the feedback. 

I've also had issues when scanning a forum that's installed in a directory. `example.com/mybb/`

I believe the http.client isn't very flexible with the input, I'm going to try to switch to the requests module and see what I can do.
